---
- hosts: all
  remote_user: root
  tasks:
    - name: ubuntu update
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist

    - name: user check
      user: name=ubuntu shell=/usr/bin/bash

- hosts: cmangos-server
  remote_user: root
  roles:
    - cmangos-classic

#- hosts: cmangos-database
#  remote_user: root
#  roles:
#    - cmangos-classicdb
